### ISSUE TITLE
java.lang.NullPointerException: intent must not be null 

### ISSUE THREAD

**Issue by SijuKJ** [derTuca/flutter_google_places_picker#10]
When the location select button clicks, app opens map screen and wait for 2 seconds and app crashing with Nullpointer exeception. 
The steps I have done are,  configured **_Maps SDK for Android_** and _**Places SDK**_ in _https://console.cloud.google.com/_ and created a API key. This API key is added in AndroidManifest.xml as meta-data.
`<meta-data android:name="com.google.android.geo.API_KEY" android:value="AI****UI"/> `

Please see the below error logs and kindly help me to resolve this issue.

```
I/Timeline(31917): Timeline: Activity_launch_request time:13065492
D/AndroidRuntime(31917): Shutting down VM
E/AndroidRuntime(31917): FATAL EXCEPTION: main
E/AndroidRuntime(31917): Process: com.example.flutterecommerce, PID: 31917
E/AndroidRuntime(31917): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=131070, result=2, data=null} to activity {com.example.flutterecommerce/com.example.flutterecommerce.MainActivity}: java.lang.NullPointerException: intent must not be null
E/AndroidRuntime(31917): 	at android.app.ActivityThread.deliv**erResults(ActivityThread.java:3813)
E/AndroidRuntime(31917): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3856)
E/AndroidRuntime(31917): 	at android.app.ActivityThread.access$1600(ActivityThread.java:151)
E/AndroidRuntime(31917): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
E/AndroidRuntime(31917): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(31917): 	at android.os.Looper.loop(Looper.java:157)
E/AndroidRuntime(31917): 	at android.app.ActivityThread.main(ActivityThread.java:5603)
E/AndroidRuntime(31917): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31917): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
E/AndroidRuntime(31917): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
E/AndroidRuntime(31917): Caused by: java.lang.NullPointerException: intent must not be null
E/AndroidRuntime(31917): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source)
E/AndroidRuntime(31917): 	at com.google.android.gms.location.places.ui.zzb.getStatus(Unknown Source)
E/AndroidRuntime(31917): 	at com.google.android.gms.location.places.ui.PlaceAutocomplete.getStatus(Unknown Source)
E/AndroidRuntime(31917): 	at com.theantimony.googleplacespicker.GooglePlacesPickerPlugin.onActivityResult(GooglePlacesPickerPlugin.kt:104)
E/AndroidRuntime(31917): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(31917): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime(31917): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime(31917): 	at android.app.Activity.dispatchActivityResult(Activity.java:6560)
E/AndroidRuntime(31917): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3809)
E/AndroidRuntime(31917): 	... 9 more
I/Process (31917): Sending signal. PID: 31917 SIG: 9
Lost connection to device.
Exited (sigterm)

```

**Comment by guyzk** [comment]
Same exact error here.

**Comment by MayurPrajapati** [comment]
Same error...
Anyone got the solution?

**Comment by subaharan** [comment]
I am also facing the same error. any fix available?

**Comment by derTuca** [comment]
The issue is stale, so I will be closing it. If anyone still encounters this issue, please re-open it.
