### ISSUE TITLE
stop working after flutter v0.9.4 upgrade

### ISSUE THREAD

**Issue by stt106** [derTuca/flutter_google_places_picker#3]
It was working before and now got error:

```
[[ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (10110): PlatformException(PLACE_AUTOCOMPLETE_ERROR, ERROR, null)
E/flutter (10110): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (10110): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (10110): <asynchronous suspension>
E/flutter (10110): #2      PluginGooglePlacePicker.showAutocomplete (package:google_places_picker/google_places_picker.dart:32:41)]
```

**Comment by derTuca** [comment]
I am going to clean up the old issues. If you still encounter issues, don't hesitate to open a new issue!
