### ISSUE TITLE
Android 4.4.2 crash: Could not find method android.app.NotificationManager.getNotificationChannel, referenced from method com.google.android.gms.common.GoogleApiAvailability.zaa

### ISSUE THREAD

**Issue by emuthomi** [derTuca/flutter_google_places_picker#5]
The example app crashes with this error log when I click the "Show Place Picker".

```

I/dalvikvm( 2652): Could not find method android.app.NotificationManager.getNotificationChannel, referenced from method com.google.android.gms.common.GoogleApiAvailability.zaa
W/dalvikvm( 2652): VFY: unable to resolve virtual method 300: Landroid/app/NotificationManager;.getNotificationChannel (Ljava/lang/String;)Landroid/app/NotificationChannel;
D/dalvikvm( 2652): VFY: replacing opcode 0x6e at 0x00b4
I/dalvikvm( 2652): Could not find method android.app.NotificationManager.getNotificationChannel, referenced from method com.google.android.gms.common.GoogleApiAvailability.setDefaultNotificationChannelId
W/dalvikvm( 2652): VFY: unable to resolve virtual method 300: Landroid/app/NotificationManager;.getNotificationChannel (Ljava/lang/String;)Landroid/app/NotificationChannel;
D/dalvikvm( 2652): VFY: replacing opcode 0x6e at 0x000e
D/dalvikvm( 2652): DexOpt: unable to opt direct call 0x0123 at 0xc2 in Lcom/google/android/gms/common/GoogleApiAvailability;.zaa
I/dalvikvm( 2652): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.GooglePlayServicesUtilLight.isUninstalledAppPossiblyUpdating
W/dalvikvm( 2652): VFY: unable to resolve virtual method 765: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
D/dalvikvm( 2652): VFY: replacing opcode 0x6e at 0x0012
I/dalvikvm( 2652): Could not find method android.content.pm.PackageManager.isInstantApp, referenced from method com.google.android.gms.common.wrappers.PackageManagerWrapper.isCallerInstantApp
W/dalvikvm( 2652): VFY: unable to resolve virtual method 770: Landroid/content/pm/PackageManager;.isInstantApp (Ljava/lang/String;)Z
D/dalvikvm( 2652): VFY: replacing opcode 0x6e at 0x002e
D/AndroidRuntime( 2652): Shutting down VM
W/dalvikvm( 2652): threadid=1: thread exiting with uncaught exception (group=0x4181bda0)
E/AndroidRuntime( 2652): FATAL EXCEPTION: main
E/AndroidRuntime( 2652): Process: com.theantimony.googleplacespickerexample, PID: 2652
E/AndroidRuntime( 2652): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=131070, result=2, data=null} to activity {com.theantimony.googleplacespickerexample/com.theantimony.googleplacespickerexample.MainActivity}: java.lang.NullPointerException: intent must not be null
E/AndroidRuntime( 2652):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3752)
E/AndroidRuntime( 2652):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3795)
E/AndroidRuntime( 2652):        at android.app.ActivityThread.access$1400(ActivityThread.java:172)
E/AndroidRuntime( 2652):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
E/AndroidRuntime( 2652):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2652):        at android.os.Looper.loop(Looper.java:146)
E/AndroidRuntime( 2652):        at android.app.ActivityThread.main(ActivityThread.java:5692)
E/AndroidRuntime( 2652):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2652):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2652):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
E/AndroidRuntime( 2652):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
E/AndroidRuntime( 2652):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2652): Caused by: java.lang.NullPointerException: intent must not be null
E/AndroidRuntime( 2652):        at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source)
E/AndroidRuntime( 2652):        at com.google.android.gms.location.places.ui.zzb.getStatus(Unknown Source)
E/AndroidRuntime( 2652):        at com.google.android.gms.location.places.ui.PlaceAutocomplete.getStatus(Unknown Source)
E/AndroidRuntime( 2652):        at com.theantimony.googleplacespicker.GooglePlacesPickerPlugin.onActivityResult(GooglePlacesPickerPlugin.kt:104)
E/AndroidRuntime( 2652):        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime( 2652):        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime( 2652):        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime( 2652):        at android.app.Activity.dispatchActivityResult(Activity.java:5734)
E/AndroidRuntime( 2652):        at android.app.ActivityThread.deliverResults(ActivityThread.java:3748)
E/AndroidRuntime( 2652):        ... 11 more
I/Process ( 2652): Sending signal. PID: 2652 SIG: 9
Lost connection to device.


```

**Comment by derTuca** [comment]
Closing this issue as a clean-up, if this reoccurs please open another issue.
